<?php

namespace Database\Seeders;

use App\Models\Insumo;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class InsumoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $insumos = [
            [
                "codigo_barra" => "1026",
                "nombre" => "PORTA BACKING AJUSTABLE",
                "marca" => "DAIKO",
                "categoria" => "SERVICIO",
                "stock" => 6.5,
                "unidad" => 1,
                "cantidad" => 6.5,
                'precio' => 10,
                'costo' => 7,
                'almacen' => "ALMACEN A",
                'id_medida' => 1,
                'id_almacen' => 1,
                'id_marca' => 1,
                'id_categoria' => 1,
            ],
            [
                "codigo_barra" => "2011",
                "nombre" => "DAMPER XP600",
                "marca" => "DAIKO",
                "categoria" => "DAIKO",
                "stock" => 25.00,
                "cantidad" => 6.5,
                "unidad" => 0,
                'precio' => 10,
                'costo' => 7,
                'almacen' => "ALMACEN A",
                'id_medida' => 1,
                'id_almacen' => 1,
                'id_marca' => 1,
                'id_categoria' => 1,
            ],
            [
                "codigo_barra" => "2015",
                "nombre" => "CAPPING XP600",
                "marca" => "DAIKO",
                "categoria" => "DAIKO",
                "stock" => 4,
                "unidad" => 0,
                'precio' => 10,
                'costo' => 7,
                'almacen' => "ALMACEN A",
                "cantidad" => 6.5,
                'id_medida' => 1,
                'id_almacen' => 1,
                'id_marca' => 1,
                'id_categoria' => 1,
            ],
            [
                "codigo_barra" => "3001",
                "nombre" => "TINTA ECOSOLVENTE CIAN 1LTS",
                "marca" => "DAIKO",
                "categoria" => "DAIKO",
                "stock" => 31000,
                "unidad" => 31,
                'precio' => 10,
                'costo' => 7,
                'almacen' => "ALMACEN A",
                "cantidad" => 6.5,
                'id_medida' => 1,
                'id_almacen' => 1,
                'id_marca' => 1,
                'id_categoria' => 1,
            ],
            [
                "codigo_barra" => "3002",
                "nombre" => "TINTA ECOSOLVENTE MAGENTA 1LTS",
                "marca" => "DAIKO",
                "categoria" => "DAIKO",
                "stock" => 8000,
                "unidad" => 1000,
                "cantidad" => 8,
                'precio' => 10,
                'costo' => 7,
                'almacen' => "ALMACEN A",

                'id_medida' => 1,
                'id_almacen' => 1,
                'id_marca' => 1,
                'id_categoria' => 1,
            ],
            [
                "codigo_barra" => "3003",
                "nombre" => "TINTA ECOSOLVENTE YELLOW 1LTS",
                "marca" => "DAIKO",
                "categoria" => "DAIKO",
                "stock" => 55,
                "unidad" => 1,
                "cantidad" => 55,
                'precio' => 10,
                'costo' => 7,
                'almacen' => "ALMACEN A",

                'id_medida' => 1,
                'id_almacen' => 1,
                'id_marca' => 1,
                'id_categoria' => 1,
            ],
            [
                "codigo_barra" => "3004",
                "nombre" => "TINTA ECOSOLVENTE BLACK 1LTS",
                "marca" => "DAIKO",
                "categoria" => "DAIKO",
                "stock" => 11000,
                "unidad" => 1100,
                "cantidad" => 11,
                'precio' => 10,
                'costo' => 7,
                'almacen' => "ALMACEN A",

                'id_medida' => 1,
                'id_almacen' => 1,
                'id_marca' => 1,
                'id_categoria' => 1,
            ],
            [
                "codigo_barra" => "3009",
                "nombre" => "LONNA BANNER 10 OZ DAIKO",
                "marca" => "DAIKO",
                "categoria" => "DAIKO",
                "stock" => 2500,
                "unidad" => 250,
                "cantidad" => 10,
                'precio' => 10,
                'costo' => 7,
                'almacen' => "ALMACEN A",

                'id_medida' => 1,
                'id_almacen' => 1,
                'id_marca' => 1,
                'id_categoria' => 1,
            ],
            [
                "codigo_barra" => "3027",
                "nombre" => "LONA BANNER 13 OZ. BLANCO/BLANCO DAIKO",
                "marca" => "DAIKO",
                "categoria" => "DAIKO",
                "stock" => 0.89,
                "unidad" => 1,
                "cantidad" => 0.89,
                'precio' => 10,
                'costo' => 7,
                'almacen' => "ALMACEN A",

                'id_medida' => 1,
                'id_almacen' => 1,
                'id_marca' => 1,
                'id_categoria' => 1,

            ],
            [
                "codigo_barra" => "3034",
                "nombre" => "LONA BANNER 13 BLACK OUT DAIKO",
                "marca" => "DAIKO",
                "categoria" => "DAIKO",
                "stock" => 0,
                "unidad" => 1,
                "cantidad" => 0,
                'precio' => 10,
                'costo' => 7,
                'almacen' => "ALMACEN A",

                'id_medida' => 1,
                'id_almacen' => 1,
                'id_marca' => 1,
                'id_categoria' => 1,
            ],
            [
                "codigo_barra" => "3039",
                "nombre" => "VINIL AUTOADHESIVO BRILLANTE 1.07/140G DAIKO",
                "marca" => "DAIKO",
                "categoria" => "DAIKO",
                "stock" => 0,
                "unidad" => 1,
                "cantidad" => 0,
                'precio' => 10,
                'costo' => 7,
                'almacen' => "ALMACEN A",

                'id_medida' => 1,
                'id_almacen' => 1,
                'id_marca' => 1,
                'id_categoria' => 1,
            ],
            [
                "codigo_barra" => "3040",
                "nombre" => "VINIL AUTOADHESIVO BRILLANTE 1.37/140 GS DAIKO",
                "marca" => "DAIKO",
                "categoria" => "DAIKO",
                "stock" => 3,
                "unidad" => 3,
                "cantidad" => 1,
                'precio' => 10,
                'costo' => 7,
                'almacen' => "ALMACEN A",

                'id_medida' => 1,
                'id_almacen' => 1,
                'id_marca' => 1,
                'id_categoria' => 1,
            ],
            [
                "codigo_barra" => "3041",
                "nombre" => "VINIL AUTOADHESIVO BRILLANTE 1.52/140G DAIKO",
                "marca" => "DAIKO",
                "categoria" => "DAIKO",
                "stock" => 1900,
                "unidad" => 100,
                "cantidad" => 19,
                'precio' => 10,
                'costo' => 7,
                'almacen' => "ALMACEN A",

                'id_medida' => 1,
                'id_almacen' => 1,
                'id_marca' => 1,
                'id_categoria' => 1,
            ],
            [
                "codigo_barra" => "3042",
                "nombre" => "VINIL AUTOADHESIVO MATE 1.40 GR 1.37",
                "marca" => "DAIKO",
                "categoria" => "DAIKO",
                "stock" => 10000,
                "unidad" => 1000,
                "cantidad" => 10,
                'precio' => 10,
                'costo' => 7,
                'almacen' => "ALMACEN A",

                'id_medida' => 1,
                'id_almacen' => 1,
                'id_marca' => 1,
                'id_categoria' => 1,
            ],
            [
                "codigo_barra" => "3043",
                "nombre" => "VINIL MICROPERFORADO ONE WAY VISION",
                "marca" => "DAIKO",
                "categoria" => "DAIKO",
                "stock" => 13000,
                "unidad" => 565.21,
                "cantidad" => 23,
                'precio' => 10,
                'costo' => 7,
                'almacen' => "ALMACEN A",

                'id_medida' => 1,
                'id_almacen' => 1,
                'id_marca' => 1,
                'id_categoria' => 1,
            ],
            [
                "codigo_barra" => "3044",
                "nombre" => "VINIL TRANSPARENTE BRILLANTE 140GSM",
                "marca" => "DAIKO",
                "categoria" => "DAIKO",
                "stock" => 20000,
                "unidad" => 1000,
                "cantidad" => 20,
                'precio' => 10,
                'costo' => 7,
                'almacen' => "ALMACEN A",

                'id_medida' => 1,
                'id_almacen' => 1,
                'id_marca' => 1,
                'id_categoria' => 1,
            ],
            [
                "codigo_barra" => "3045",
                "nombre" => "VINIL TRANSPARENTE MATE 140 GSM",
                "marca" => "DAIKO",
                "categoria" => "DAIKO",
                "stock" => 5000,
                "unidad" => 1000,
                "cantidad" => 5,
                'precio' => 10,
                'costo' => 7,
                'almacen' => "ALMACEN A",

                'id_medida' => 1,
                'id_almacen' => 1,
                'id_marca' => 1,
                'id_categoria' => 1,
            ],
            [
                "codigo_barra" => "3046",
                "nombre" => "FLOORGRAPHIC 140GSM (METRO LINEAL)",
                "marca" => "DAIKO",
                "categoria" => "DAIKO",
                "stock" => 1000,
                "unidad" => 1000,
                "cantidad" => 1,
                'precio' => 10,
                'costo' => 7,
                'almacen' => "ALMACEN A",

                'id_medida' => 1,
                'id_almacen' => 1,
                'id_marca' => 1,
                'id_categoria' => 1,
            ]
        ];

        foreach ($insumos as $key => $insumo) {
            Insumo::create($insumo);
        }
    }
}
