<?php

namespace Database\Seeders;

use App\Models\Marca;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MarcaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $marcas = [
            "Apple",
            "Samsung",
            "Sony",
            "Microsoft",
            "Google",
            "Amazon",
            "Nike",
            "Adidas",
            "Puma",
            "Reebok",
            "Zara",
            "H&M",
            "Levi's",
            "Gucci",
            "Louis Vuitton",
            "Chanel",
            "Dior",
            "Versace",
            "Rolex",
            "Omega",
            "Cartier",
            "Mercedes-Benz",
            "BMW",
            "Audi",
            "Toyota",
            "Honda",
            "Ford",
            "Chevrolet",
            "Volkswagen",
            "Hyundai",
            "Kia",
            "Tesla",
            "Coca-Cola",
            "Pepsi",
            "Starbucks",
            "McDonald's",
            "Burger King",
            "KFC",
            "Subway",
            "Nestlé",
            "Unilever",
            "Procter & Gamble",
            "Johnson & Johnson",
            "L'Oréal",
            "Gillette",
            "Colgate",
            "Oral-B",
            "Philips",
            "Bosch",
            "Siemens",
            "LG",
            "Whirlpool",
            "Electrolux",
            "HP",
            "Dell",
            "Lenovo",
            "Acer",
            "Asus",
            "Nvidia",
            "Intel",
            "AMD",
            "Canon",
            "Nikon",
            "Fujifilm",
            "Panasonic",
            "Miele",
            "Dyson",
            "IKEA",
            "LEGO",
            "Mattel",
            "Hasbro",
            "Disney",
            "Netflix",
            "Spotify",
            "YouTube",
            "Facebook",
            "Instagram",
            "Twitter",
            "TikTok",
            "WhatsApp",
            "Zoom",
            "Adobe",
            "Oracle",
            "SAP",
            "IBM",
            "Cisco",
            "Qualcomm",
            "3M",
            "Caterpillar",
            "General Electric",
            "Boeing",
            "Airbus",
            "Shell",
            "ExxonMobil",
            "BP",
            "Chevron",
            "TotalEnergies",
            "Vodafone",
            "Verizon",
            "AT&T",
            "T-Mobile",
            "Salesforce",
            "Shopify",
            "Paypal",
            "Visa",
            "Mastercard",
            "American Express",
            "UPS",
            "FedEx"
        ];

        foreach ($marcas as $key => $value) {
            Marca::create(['nombre' => $value]);
        }
    }
}
